### ISSUE TITLE
WTF why is the application running, even through my intellij is closed?

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/kotlin-for-fun#15]
- [ ] find the source of this magic and deactivate it

**Comment by Bantolomeus** [comment]
computer restart fixed it, puh, was spooky

**Comment by Husterknupp** [comment]
`ps aux | grep java` will reveal running java processes. Next time hit this on the command line and u will find a process id. 

`kill -9 ${processId}` will end the process. Quitting IntelliJ might not necessarily also quit the process of your app

**Comment by Bantolomeus** [comment]
Thank you for this information. Will do this next time
