### ISSUE TITLE
implement command pattern

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/kotlin-for-fun#25]
- [x] implement rest endpoint for calculator 
- [x] implement service for calculator
- [x] implement all the command pattern classes and interfaces 
- [x] implement logic for different commands

**Comment by Husterknupp** [comment]
cool idea to implement the calculator via command pattern. Decouples the input from the calculation, hence the input endpoint is not blocked even for expensive calculations

**Comment by Bantolomeus** [comment]
@Husterknupp I refactored quite a lot, do you find it better now? Now it is more decoupled
