### ISSUE TITLE
give back more than one return value on rest call

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/kotlin-for-fun#6]
- [ ] find out how to give back a json with more than only the distribution

**Comment by Husterknupp** [comment]
For instance You could assemble a json in the controller, wrap your distribution into an object together with more keys and return the json as string as the reponse object. 

`{distribution: yourConcreteDistribution, otherKey: otherValue}`

Or you build a wrapper class that consists of the distribution and other fields. The controller would create an instance of that class and return it as the response object

**Comment by Bantolomeus** [comment]
The second half sounds clean. But I wanna see results. When do I want to see them? NOW
